apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:

      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.1
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
        ports:
        - containerPort: 2181
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
        volumeMounts:
          - name: kafka-storage-log
            mountPath: /var/lib/zookeeper/log
          - name: kafka-storage-data
            mountPath: /var/lib/zookeeper/data

      - name: kafka
        image: confluentinc/cp-kafka:7.3.1
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "localhost:2181"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kafka-svc:9092
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"

          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "0"

        volumeMounts:
          - name: kafka-storage-log
            mountPath: /var/log/kafka
          - name: kafka-storage-data
            mountPath: /var/lib/kafka/data



      - name: kafka-ui
        image: provectuslabs/kafka-ui:v0.5.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: KAFKA_CLUSTERS_0_NAMEl
            value: local
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: localhost:29092
          - name: KAFKA_CLUSTERS_0_ZOOKEEPER
            value: localhost:2181
          - name: KAFKA_CLUSTERS_0_READONLY
            value: "false"
          - name: SERVER_PORT
            value: "8888"

      volumes:
        - name: kafka-storage-log
          persistentVolumeClaim:
            claimName: kafka-storage-log-pvc
        - name: kafka-storage-data
          persistentVolumeClaim:
            claimName: kafka-storage-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  selector:
    app: kafka
  ports:
  - name: kafka-broker
    port: 9092
    targetPort: 9092
  - name: kafka-ui
    port: 8888
    targetPort: 8888  


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-storage-log-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-storage-data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
